### ISSUE TITLE
`charmcraft.upload()` will only work in charmcraft 2.x

### ISSUE THREAD

**Issue by ca-scribner** [lucabello/noctua#2]
using the `docker://name:tag` format for [`charmcraft upload-resource --image`](https://github.com/lucabello/noctua/blob/8f451ed0d6fdd50aeb5a774770fb832079054bcf/src/services/charmcraft.py#L369) only works in charmcraft 2. 
 Not sure if that is a bug or by design from charmcraft. 

As is, using noctua in place of charming-actions/upload will introduce a regression compared to charming-actions/upload because the charming actions upload [pulls the image locally first](https://github.com/canonical/charming-actions/blob/934193396735701141a1decc3613818e412da606/src/services/charmcraft/charmcraft.ts#L129) then uses syntax that works on charmcraft 2 and 3.

**Comment by lucabello** [comment]
This syntax is supposed to work with Charmcraft 3, and it does on `3.2.0.post19+g13a3e049` (currently `latest/edge`). The regression was actually in `3.1.2` (currently `latest/stable`), but this API has been tested with `3.2.0.post19+g13a3e049` and Alex confirmed it should work.

Leaving it open until you can confirm, but if it doesn't work for you, we need to raise the issue to Charmcraft :)
